### ISSUE TITLE
Typescript required versions

### ISSUE THREAD

**Issue by danielfx90** [helmetjs/helmet#448] opened 2023-12-20 15:13 UTC
Hi!

I faced the `Cannot find module 'helmet' or its corresponding type declarations.` error. I feel that there are some Typescript version requirements that should be documented somewhere.

- `v6.0.0 <= Helmet < v6.2.0`: Supports TS v4 in general (I did not test it with TS below v4).
- `v6.2.0 <= Helmet`: Requires TS v4.7.2 and above.

Hope it helps! Cheers!

**Comment by EvanHahn** [comment] 2023-12-20 18:21
Thanks for this! I'll see about improving this or, at worst, adding some official documentation.

**Comment by EvanHahn** [comment] 2024-02-17 15:48
I couldn't reproduce this. I installed `typescript@4.6.4` (the version prior to v4.7.2) and `helmet@6.2.0` and things compiled just fine.

Given that (1) I couldn't reproduce this (2) you can upgrade to the latest `typescript@4` to fix your problem (3) Helmet v6 is no longer supported, I'm going to close this issue.

Let me know if that's wrong and I'll reopen.

**Closed by EvanHahn** 2024-02-17 15:48 UTC
