### ISSUE TITLE
Export typings for individual middleware options

### ISSUE THREAD

**Issue by billyjanitsch** [helmetjs/helmet#425] opened 2023-05-15 23:04 UTC
Hi! Currently, Helmet [exports the top-level options type](https://github.com/helmetjs/helmet/blob/88766cdd7b769e2fc668154d3e964dd1ef1be016/index.ts#LL35C1-L35C1) (`HelmetOptions`) but not any of the constituent middleware options types (`ContentSecurityPolicyOptions`, etc.).

As a workaround, it's possible to extract them from the top-level type, but doing so isn't very ergonomic because they're [mixed in with booleans and null values](https://github.com/helmetjs/helmet/blob/88766cdd7b769e2fc668154d3e964dd1ef1be016/index.ts#L36), so you have to do something like:

```ts
import {type HelmetOptions} from 'helmet'

type ContentSecurityPolicyOptions = Extract<HelmetOptions['contentSecurityPolicy'], object>
```

Would you be open to exporting all of the middleware options types so that this isn't necessary?

**Comment by EvanHahn** [comment] 2023-05-16 12:22
Would something like this work for you?

```ts
type ContentSecurityPolicyOptions = Parameters<typeof helmet.contentSecurityPolicy>[0];
```

**Comment by EvanHahn** [comment] 2023-07-17 12:20
I'm going to close this issue because there hasn't been much movement on it. Let me know if you'd like me to reopen.

**Closed** 2023-07-17 12:20 UTC

**Comment by judithhartmann** [comment] 2023-08-11 11:52
Hey @EvanHahn,
we are currently upgrading from 6.1.0 to 6.2.0.

Before we were able to import ContentSecurityPolicyOptions through:
```ts
import { ContentSecurityPolicyOptions } from 'helmet/dist/types/middlewares/content-security-policy';
```
not pretty but it did the job.

in 6.2.0 I tried both:
```ts
type ContentSecurityPolicyOptions = Parameters<typeof helmet.contentSecurityPolicy>[0];
```
and 
```ts
import {type HelmetOptions} from 'helmet'

type ContentSecurityPolicyOptions = Extract<HelmetOptions['contentSecurityPolicy'], object>
```
neither of the 2 suggested solutions work, due to the following error:
TS4023
```
Exported variable 'contentSecurityPolicies' has or is using name 'ContentSecurityPolicyOptions' from external module `[PROJECT_PATH]/node_modules/helmet/index" but cannot be named.
``` 
most likely due to `ContentSecurityPolicyOptions` not being exported

is there a way, you can export the in between interfaces as well?

**Comment by EvanHahn** [comment] 2023-08-11 15:15
@judithhartmann Does something like this work for you?

```typescript
import type { HelmetOptions } from "helmet";

type ContentSecurityPolicyOptions = HelmetOptions["contentSecurityPolicy"];

const cspOptions: ContentSecurityPolicyOptions = {
  directives: {
    defaultSrc: ["'self'"],
    // ...
  },
};
```

**Comment by EvanHahn** [comment] 2023-08-11 15:32
@judithhartmann Does this happen with the latest version of Helmet, too? If so, could you open a new issue with code that reproduces this problem?

**Comment by judithhartmann** [comment] 2023-08-11 15:33
Yes it does. I will open an issue
