### ISSUE TITLE
Cannot find module './config.json'

### ISSUE THREAD

**Issue by martianmartian** [helmetjs/helmet#104] opened 2015-10-07 06:23 UTC
I guess my heroku has been caching the old version for a while, when i updated, it came out a new error. 

Any thought?

Searching 2768 files for "./config.json"
```
/Users/macbookpro/Desktop/langtime3/node_modules/helmet/index.js:
    2  
    3  var crossdomain = require('./lib/deprecated-crossdomain');
    4: var config = require('./config.json');
    5  
    6  function helmet() {

/Users/macbookpro/Desktop/langtime3/node_modules/helmet/test/index.js:
    1  var helmet = require('..');
    2: var config = require('../config.json');
    3  
    4  var assert = require('assert');

2 matches across 2 files
```

**Comment by EvanHahn** [comment] 2015-10-07 15:26
Do you have a stack trace you can show?

**Comment by iamwave007** [comment] 2015-10-09 14:11
strange that I can't reproduce the error if i break down the app to the simplest part. It seems the erro isn't from the helmet itself.. still looking for it.. hold on

**Comment by EvanHahn** [comment] 2015-10-09 15:04
Could it be that you're adding a `require` hook?

**Comment by iamwave007** [comment] 2015-10-12 14:29
Is that supposed to be the cause of the issue? I don't even know what it is..
It's been spooky lately. I can't push changes for the moment before fixing it..

**Comment by EvanHahn** [comment] 2015-10-12 14:31
Can you see the logs with `heroku logs`?

**Comment by rdooh** [comment] 2015-10-26 20:02
I get this from my terminal when running some Jest unit tests...
    Cannot find module './lib/config' from ... /node_modules/helmet/node_modules/helmet-csp/index.js
In my case, I can probably maneuver around it... but might help... ref'd from dependency

**Comment by EvanHahn** [comment] 2015-10-26 20:12
@rdooh I'd love to debug this but I'm really unsure what the issue is. Could you create a sample repo that shows this error?

**Comment by EvanHahn** [comment] 2015-10-26 20:12
Also—what version of Node are people using?

**Comment by rdooh** [comment] 2015-10-26 21:45
node 4.1.1
will take a look at a sample later - but it looks like helmet-csp tries to require a config.json file and it's breaking for me, but only in Jest tests.  Works fine in the application itself.

**Comment by EvanHahn** [comment] 2015-10-26 21:54
Could it be related to this Jest issue?
https://github.com/facebook/jest/issues/353

**Comment by rdooh** [comment] 2015-10-26 23:06
brilliant :) absolutely - just added json to the moduleFileExtensions and it works

    "moduleFileExtensions": ["js", "json", "node"]

so not at all a helmet thing :) - maybe there's a similar condition with the original issue from @martianmartian

**Comment by EvanHahn** [comment] 2015-11-01 15:52
@martianmartian Any updates?

**Comment by EvanHahn** [comment] 2015-11-12 06:26
@martianmartian I'm going to close this issue for now. Feel free to reopen it if you're still having trouble!

**Closed by EvanHahn** 2015-11-12 06:26 UTC
