### ISSUE TITLE
can i use es6-style import to import helmet?

### ISSUE THREAD

**Issue by oshihirii** [helmetjs/helmet#339] opened 2021-11-28 07:32 UTC
this site:

https://helmetjs.github.io/

only shows:

    const helmet = require("helmet");

but i am in a quandary because:

- some packages only show ES6 style imports, eg:

https://date-fns.org/

    import { format, formatDistance, formatRelative, subDays } from 'date-fns'     

- the node docs say that:

> ECMAScript modules are the official standard format to package JavaScript code for reuse.   
> Modules are defined using a variety of import and export statements.  

source:  https://nodejs.org/dist/latest-v17.x/docs/api/esm.html#modules-ecmascript-modules

i referred to this issue from 2016 and was wondering if there has been an update since then?  

https://github.com/helmetjs/helmet/issues/141

i am using babel to transpile server-side code.

so i thought i should be able to use `import` statements and it will convert them to the relevant `require` statements.

however, when i try and use `import` statements in my own middleware files like:

> import { format } from 'date-fns';  

i get errors like:  

> SyntaxError: Cannot use import statement outside a module  

thank you.

**Comment by EvanHahn** [comment] 2021-11-28 15:45
You cannot. However, the next major version of Helmet should support this.

I'm going to close this because it's a duplicate of #320. Please keep an eye out for Helmet 5's beta, because I'll want feedback on the module experience.

**Closed by EvanHahn** 2021-11-28 15:45 UTC

**Comment by EvanHahn** [comment] 2021-12-05 21:48
I just released Helmet v5.0.0-beta.1 which includes this change. You can now use ES6-style imports. Please give it a try with `npm install helmet@5.0.0-beta.1` and let me know if there are any problems! Feel free to reply here or email me@evanhahn.com with any feedback.

**Comment by EvanHahn** [comment] 2022-01-02 18:06
You can now use ECMAScript modules with `helmet@5`.
