### ISSUE TITLE
Invalid destructuring assignment target

### ISSUE THREAD

**Issue by TheCuteFoxxy** [helmetjs/helmet#321] opened 2021-06-18 14:55 UTC
Anytime [] is used as part of options, it causes the server to crash with "Invalid destructuring assignment target". Encountered no matter what is changed.

Example Code: 
```
app.use(
  helmet.contentSecurityPolicy({
    useDefaults: false,
    directives: {
      defaultSrc: ["'self'"],
      scriptSrc: ["'self'", "https://ajax.cloudflare.com", "https://cdnjs.cloudflare.com"],
      objectSrc: ["'none'"],
      upgradeInsecureRequests: [],
    },
  })
);
```

**Comment by EvanHahn** [comment] 2021-06-18 22:23
Sorry you're running into this. I won't have time to dig in for a few days, but it's on my list.

The first thing I'll do when digging in: create a small sample app that tries to reproduce the problem. If you want to go ahead and do that, you could save me some time.

If anyone else is experiencing this issue, let me know.

**Comment by EvanHahn** [comment] 2021-06-19 16:21
I just made a sample app with the following code (this is the entire file):

```js
const express = require("express");
const helmet = require("helmet");

const port = process.env.PORT || 9999;

const app = express();

app.use(
  helmet.contentSecurityPolicy({
    useDefaults: false,
    directives: {
      defaultSrc: ["'self'"],
      scriptSrc: [
        "'self'",
        "https://ajax.cloudflare.com",
        "https://cdnjs.cloudflare.com",
      ],
      objectSrc: ["'none'"],
      upgradeInsecureRequests: [],
    },
  })
);

app.get("/", (req, res) => {
  res.send("Hello world");
});

app.listen(port, () => {
  console.log("App started on port " + port);
});
```

I'm not seeing any errors when I hit this server. If you run that code, do you see the same error message?

Is it possible that you're on an old version of something? Version numbers of everything I'm running right now:

- `helmet` v4.6.0
- `express` v4.17.1
- Node v16.3.0

I'm not sure what the problem is, but let's try to get to the bottom of it.

**Comment by TheCuteFoxxy** [comment] 2021-06-20 15:35
I will run it today and see what happens.

**Comment by TheCuteFoxxy** [comment] 2021-06-21 00:49
Just ran it with that, working just fine. Do you think it would possibly be caused by trying to use it along with other helmet options rather than using helmet.contentSecurityPolicy() alone?

**Comment by EvanHahn** [comment] 2021-06-21 03:50
Maybe! Do you have more information about the error, such as a stack trace?

**Comment by EvanHahn** [comment] 2021-06-21 13:39
A couple more ideas:

1. Are you on the latest versions of things? Is it possible that you're on an old version which is causing some issues?
1. Does the problem persist if you remove Helmet? If so, what if you only remove the CSP middleware?

**Comment by EvanHahn** [comment] 2021-07-04 17:13
Any updates here? No worries if not, but I might close the issue if there's no more investigation to be done.

**Comment by TheCuteFoxxy** [comment] 2021-07-04 17:20
My enviroment is running Node.js v14, Python 3.7.3, and Java 11.0.9.1. Latest helmet version (I ended switching packages from helmet). I can confirm the issue only occurs when used with other helmet options in the same helmet object (see below)
```
app.use(
  referrerPolicy: { policy: "no-referrer" },
  helmet.contentSecurityPolicy({
    useDefaults: false,
    directives: {
      defaultSrc: ["'self'"],
      scriptSrc: [
        "'self'",
        "https://ajax.cloudflare.com",
        "https://cdnjs.cloudflare.com",
      ],
      objectSrc: ["'none'"],
      upgradeInsecureRequests: [],
    },
  })
);
```
You can close this if you would like, but this is about all the information I have on this.

**Comment by EvanHahn** [comment] 2021-07-04 17:26
That code looks like it has a syntax error, which could explain your issue. Is there any chance you have a stack trace or a way to reproduce this? I'd love to fix the problem but I don't think I know where to start.

**Comment by TheCuteFoxxy** [comment] 2021-07-04 17:28
Unfortunately none of my environments have helmet anymore so I can't get a
stack trace for it.

**Comment by EvanHahn** [comment] 2021-07-04 17:29
Okay. I'm going to close this issue because I don't think there's more to be done here, but if you (or anyone else reading) has this problem and a stack trace, I'm happy to reopen and get to the bottom of this.

Sorry you ran into this and dropped Helmet, but glad you solved your problem.

**Closed by EvanHahn** 2021-07-04 17:29 UTC
Labels: needs more information
