### ISSUE TITLE
Add require-trusted-types-for directive

### ISSUE THREAD

**Issue by deser** [helmetjs/helmet#219] opened 2020-05-25 10:00 UTC
See here for description: https://web.dev/trusted-types/#create-a-trusted-type-policy

**Comment by EvanHahn** [comment] 2020-05-25 12:32
This is a duplicate of https://github.com/helmetjs/csp/issues/104, so I'm going to close this issue and move discussion there.

In short: I'm going to add this in the next major version of Helmet, which I hope to release in the next month.

**Closed by EvanHahn** 2020-05-25 12:32 UTC

**Comment by jeffal** [comment] 2020-09-14 17:01
Hello @EvanHahn, did this get added to Helmet? I do not see any examples how to add a trusted type policy. Thank you!

**Comment by EvanHahn** [comment] 2020-09-14 20:13
@jeffal This was added in Helmet 4.

For example:

```js
app.use(
  helmet({
    contentSecurityPolicy: {
      directives: {
        // ...
        "require-trusted-types-for": ["'script'"],
      },
    },
  })
);
```

More accurately, validation was removed from Helmet 4, allowing you to add any directive you want. Helmet supports any directive you want to set.

**Comment by I-keep-trying** [comment] 2022-03-15 15:34
This directive does not seem to work for me.

```js
app.use(
  helmet.contentSecurityPolicy({
    directives: {
      'img-src': ["'self'", 'flagcdn.com', 'upload.wikimedia.org'], // this works on its own
      'require-trusted-types-for': ["'script'"], // adding this line breaks everything, site won't render
      //'require-trusted-types-for': ['script'], // site renders, but header is invalid
    },
  })
)
```
I tried using only single quotes for 'script' and my website didn't break, but the CSP evaluator report did  not recognize the header, and the header did not look right since there were no single quotes around the value 'script'.  All the other directives containing the value 'script' had single quotes.

**Comment by EvanHahn** [comment] 2022-03-15 17:04
@I-keep-trying Sounds like this isn't a Helmet issue. Please feel free to open a new issue if that's wrong, though! Happy to help.
